services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - orbit_dragonfly_data:/data

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: orbit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - orbit_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/orbit
      DATABASE_SSL: "false"
      DRAGONFLY_URL: redis://dragonfly:6379
    depends_on:
      - db
      - dragonfly
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      ORBIT_API_INTERNAL_URL: http://api:3001
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  orbit_postgres_data:
  orbit_dragonfly_data:
